removing ambiguity in readme
tuladhar/multi-threaded-google-ban-checker pull request #7
Opened 2020-10-08 08:45 UTC by meteora2002

this is my first github contribution ,so please feel free to give your constructive feedback

2020-10-09 07:14 UTC, tuladhar commented
Congratulation @meteora2002 on your first contributions. I've left some comments, please check.

2020-10-09 07:17 UTC, tuladhar requested changes

2020-10-09 07:17 UTC, tuladhar commented on README.md
> +# This is a Google account ban checker
I suggest, these to be added under NOTES. For e.g:

**NOTE:**
- This is not a Google account, domain or advertisements ban checker

2020-10-09 07:17 UTC, tuladhar commented on README.md
> +#### IMPORTANT NOTE
Similarly to above, let's use bolded NOTE section, and not make the text very big.

2020-10-09 07:17 UTC, tuladhar commented on README.md
> +####PLease make sure your username and password exist here before using this
Similarly as above, let's add it to bolded NOTES section.

2020-10-09 07:17 UTC, tuladhar commented on README.md
> +- You will be notified once a ban is detected
This looks good.

2020-10-09 07:17 UTC, tuladhar commented on README.md
> +## TIPS FOR UPDATING
Let's remove this, as it's not mandatory to mention it.

2020-10-09 07:26 UTC, meteora2002 commented
done

2020-10-09 07:27 UTC, meteora2002 commented
@tuladhar please accept the pull requests

2020-10-10 17:46 UTC, meteora2002 commented
@tuladhar  please check my pull request now

2020-10-12 06:25 UTC, meteora2002 commented
@tuladhar  please check my pull request

2020-10-12 07:29 UTC, tuladhar requested changes
Left one comment. Besides that, looks good to merge!

2020-10-12 07:29 UTC, tuladhar commented on README.md
> +####Always update the files before using this
Let's also add this to note section.

2020-10-12 07:40 UTC, meteora2002 commented
done

2020-10-12 07:40 UTC, meteora2002 commented
@tuladhar please check it now

2020-10-12 09:13 UTC, tuladhar approved these changes

2020-10-12 09:13 UTC, tuladhar commented
Thanks @meteora2002. Merged!

2020-10-12 09:14 UTC, merged